kids/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from kid import views, feed
from django.contrib.auth.views import *
admin.autodiscover()

urlpatterns = [
    url(r'^$', views.home),
    url(r'^schedule/$', views.schedule),
    url(r'^search/$', views.search),
    url(r'^add/$', views.add),
    url(r'^watch/([\%\w|\s]+)/$', views.home),
    url(r'^watch/([\%\w|\s]+)/([\%\w|\s]+)/$', views.home),
    url(r'^delete/(\d+)/$', views.delete,name='delete'),
    url(r'^detail/(\d+)/$', views.detail,name='detail'),
    url(r'^detail/(\d+)/like/$', views.detail_like,name='detail_like'),
    url(r'^detail/(\d+)/favorite/$', views.detail_favorite,name='detail_favorite'),
    url(r'^myfavorite/$', views.myfavorite,name='myfavorite'),
    url(r'^mydelete/(\d+)$', views.mydelete,name='mydelete'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feed/$', feed.KidFeed()),
    # user
    url(r'^contact/$', views.contact),
    url(r'^login/$', views.login_page), # 'django.contrib.auth.views.login'
    url(r'^logout/$',views.logout_page),
    url(r'^profile/$',views.user_profile_view),
    url(r'^register/$',views.register_page),
    url(r'^register/success/$',views.register_success),
    url(r'^changepassword/$',views.change_password),
    url(r'^resetpassword/$', views.reset_password, name='reset'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{'post_reset_redirect':'/login','template_name':'registration/reset_confirm.html'},name='reset_confirm'),
    url(r'^password/done/$', password_reset_complete,{'template_name':'registration/reset_complete.html'},name='reset_complete'),
    url(r'^password/reset/done/$', password_reset_done,name='reset_done'),

]


handler404 = 'kid.views.page_not_found_view'
handler500 = 'kid.views.page_not_found_view'

kid/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category1(models.Model):
    title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.title

class Category2(models.Model):
    title = models.CharField(max_length=200)
    parent_category = models.ForeignKey(Category1)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        
class Kid(models.Model):
    title = models.CharField(max_length=200)
    url = models.URLField()
    image_url = models.CharField(max_length=400)
    create_date = models.DateTimeField(default=timezone.now)
    update_date =  models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category2)
    youtube_id = models.CharField(max_length=100, default='')
    view_count = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return self.url

class KidUser(models.Model):
    kid_user = models.ForeignKey(User)
    address = models.CharField('주소',max_length=200)
    invalid_password_count = models.IntegerField('비밀번호 실패횟수',default=0)
    last_login_date = models.DateTimeField('마지막접속일',default=timezone.now)
    GENDER_CHOICE =(('M','남자'),('F','여자'))
    gender = models.CharField('성별',max_length=1,default='M',choices=GENDER_CHOICE)
    birthday = models.CharField('생년월일',max_length=10,default='2000-01-01')
    class Meta:
        verbose_name = "KidUser"
        verbose_name_plural = "KidUsers"

    def __unicode__(self):
        return self.kid_user.username


class Favorite(models.Model):
    fav_user = models.ForeignKey(KidUser)
    fav_kid = models.ForeignKey(Kid)  
    update_date = models.DateTimeField('수정일',default=timezone.now)

    

kid/forms.py
# -*- encoding:utf-8 -*-
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from .models import KidUser

class ViewUserProfile(ModelForm):
    class Meta:
        model=KidUser
        fields = ['kid_user','address','gender','birthday']

    def __init__(self, *args, **kwargs):
        super(ViewUserProfile, self).__init__(*args, **kwargs)
        years = [ year+1940 for year in range(100)]
        
        self.fields['kid_user'].widget = forms.HiddenInput(attrs={'readonly':'readonly'})
        self.fields['birthday'].widget = forms.SelectDateWidget(years=years)
        

class RegistrationForm(forms.Form):
    username=forms.CharField(label='아이디',max_length=30,widget=forms.TextInput(attrs={'class' : 'form-control'}))
    email=forms.EmailField(label='Email',widget=forms.TextInput(attrs={'class' : 'form-control'}))
    password1=forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(attrs={'class' : 'form-control'})    
    )
    password2=forms.CharField(
        label='비밀번호(확인)',
        widget=forms.PasswordInput(attrs={'class' : 'form-control'})
    )
    # clean_<field> : valid field
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1=self.cleaned_data['password1']
            password2=self.cleaned_data['password2']
            if password1==password2:
                return password2
            else:
                raise forms.ValidationError('password does not match')
        else:
            raise forms.ValidationError('No passwrod1')

    def clean_username(self):
        username=self.cleaned_data['username']
        if not re.search(r'\w+$',username):
            raise forms.ValidationError('user name allows charactor, number, underscore')
        
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('already exists username')

    def clean_email(self):
        email=self.cleaned_data['email']        
        try:
            User.objects.get(email=email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError('already exists email')
     

kid/views.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils.translation import gettext as _
from django.utils.http import urlquote
from django.template import RequestContext

from django.contrib.auth import logout, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import *
from django.contrib.auth.decorators import login_required

from django.shortcuts import render,render_to_response, redirect,get_object_or_404

from django.core.paginator import Paginator
from django.db.models import Q

from kid.models import *
from kid.forms import *

from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse
from datetime import datetime

login_url='/login'
ITEMS_PER_PAGE=10
PAGE_COUNT = 5

def home(request, cat_name1='All', cat_name2=''):
    search_field = ''
    category1 = Category1.objects.order_by('title')
    if cat_name2 != '':
        cat2=get_object_or_404(Category2,title=cat_name2)
        kids_items=cat2.kid_set.order_by('-update_date')
    else:
        if cat_name1 != 'All' and cat_name1 != '':
            cat1=Category1.objects.filter(title=cat_name1)
            kids_items =Kid.objects.select_related('category__parent_category').filter(category__parent_category__in=cat1)
        else:
            kids_items = Kid.objects.order_by('-update_date')

    paginator=Paginator(kids_items,ITEMS_PER_PAGE)

    try:
        page=int(request.GET['page'])
    except:
        page=1
    try:
        kids_items=paginator.page(page)
    except:
        raise Http404

    page_list = []
    has_prev10=False
    has_next10=False
    prev_page10=0
    next_page10=0

    total_page = paginator.num_pages
    if total_page > PAGE_COUNT and page + PAGE_COUNT < total_page:
        has_next10 = True
        next_page10 = (( page + PAGE_COUNT ) // PAGE_COUNT) * PAGE_COUNT + 1

    if page > PAGE_COUNT:
        has_prev10 = True
        prev_page10 = (( page - PAGE_COUNT ) // PAGE_COUNT) * PAGE_COUNT + 1

    from_page = ( page // PAGE_COUNT ) * PAGE_COUNT + 1
    

    if from_page + PAGE_COUNT < total_page:
        page_size = PAGE_COUNT
    else:
        page_size = total_page - from_page + 1

    for i in range(page_size):
        page_list.append((i+from_page))

    context = {  'category1': category1,
               'kids_items': kids_items,
               'cat_name1' : cat_name1,
               'cat_name2' : cat_name2,
               'search_field' : search_field,
               'show_paginator':paginator.num_pages>1,
               'has_prev':kids_items.has_previous(),
               'has_next':kids_items.has_next(),
               'page':page,
               'pages':paginator.num_pages,
               'page_list' : page_list,
               'next_page':page+1,
               'prev_page':page-1,
               'has_prev10':has_prev10,
               'has_next10':has_next10,
               'prev_page10':prev_page10,
               'next_page10':next_page10,
              }
    return render(request,'search.html', context)

@permission_required('kid.add_kid')
def schedule(request):
    search_field = ''
    if 'search_field' in request.GET:
        if request.GET['search_field'] is not None:
            search_field=request.GET['search_field']

    page = '1'
    if 'page' in request.GET:
        if request.GET['page'] is not None:
            page=request.GET['page']

    page_url = '&page=' + page

    category1 = Category1.objects.order_by('title')
    category2 = Category2.objects.order_by('title')

    from bs4 import BeautifulSoup
    import urllib
    import sys

    if sys.version_info[0] == 3:
        from urllib.request import urlopen
    else:
        # Not Python 3 - today, it is most likely to be Python 2
        # But note that this might need an update when Python 4
        # might be around one day
        from urllib import urlopen

    kids_items = []
    if search_field != '':
        youtube_url ='https://www.youtube.com'
        url = youtube_url + '/results?search_query=' + urlquote(search_field) + page_url
        
        html_doc = urllib.urlopen(url)

        soup = BeautifulSoup(html_doc, "html.parser")
        links = soup.findAll('div', attrs={'class':'yt-lockup-dismissable'})

        item_id = 0
        for link in links:
            title = link.find('h3').find('a')['title']
            h_url = youtube_url + link.find('h3').find('a')['href']
            i_url = link.find('div',attrs={'class':'video-thumb'}).find('img')
            image_url=''
            try:
                if i_url['data-thumb'] != '':
                    image_url=i_url['data-thumb']
                else:
                    image_url=i_url['src']
            except:
                image_url=i_url['src']

            kids_items.append(( item_id, title, h_url, image_url ))
            item_id += 1

    context = {'category1' : category1,
               'category2' : category2,
               'kids_items' : kids_items,
               'search_field' : search_field,
               'page' : page,
              }
    return render(request, 'schedule.html', context)

def search(request):
    category1 = Category1.objects.order_by('title')
    search_field = ''
    if 'search_field' in request.GET:
        if request.GET['search_field'] is not None:
            search_field = request.GET['search_field']
            kids_items = Kid.objects.filter(title__icontains=search_field).order_by('-update_date')
    else:
        kids_items = Kid.objects.order_by('-update_date')

    paginator=Paginator(kids_items,ITEMS_PER_PAGE)

    try:
        page=int(request.GET['page'])
    except:
        page=1
    try:
        kids_items=paginator.page(page)
    except:
        raise Http404

    page_list = []
    has_prev10=False
    has_next10=False
    prev_page10=0
    next_page10=0
    from_page=0
    total_page = paginator.num_pages
    if total_page > PAGE_COUNT and page + PAGE_COUNT < total_page:
        has_next10 = True
        next_page10 = (( page + PAGE_COUNT ) // PAGE_COUNT) * PAGE_COUNT + 1

    if page > PAGE_COUNT:
        has_prev10 = True
        prev_page10 = (( page - PAGE_COUNT ) // PAGE_COUNT) * PAGE_COUNT + 1

    from_page = int( page // PAGE_COUNT ) * PAGE_COUNT + 1

    if from_page + PAGE_COUNT < total_page:
        page_size = PAGE_COUNT
    else:
        page_size = total_page - from_page + 1

    page_size = int(page_size)

    for i in range(page_size):
        page_list.append((i+from_page))

    context = {'category1' : category1,
               'kids_items' : kids_items,
               'search_field' : search_field,
               'show_paginator':paginator.num_pages>1,
               'has_prev':kids_items.has_previous(),
               'has_next':kids_items.has_next(),
               'page':page,
               'pages':paginator.num_pages,
               'page_list' : page_list,
               'next_page':page+1,
               'prev_page':page-1,
               'has_prev10':has_prev10,
               'has_next10':has_next10,
               'prev_page10':prev_page10,
               'next_page10':next_page10,
              }
    return render(request, 'search.html', context)


def add(request):
    '''
    search youtube and add youtube url
    '''
    kid_titles = request.POST.getlist('kid_title')
    kid_urls = request.POST.getlist('kid_url')
    kid_images = request.POST.getlist('kid_image')
    checks = request.POST.getlist('check')
    cat2 = request.POST['category2']
    category2 = get_object_or_404(Category2,title=cat2)

    for check in checks:
        if check:
            id = int(check)
            kid_title = kid_titles[id]
            kid_url = kid_urls[id]
            kid_image = kid_images[id]
            youtube_id = kid_urls[id].split('?')[1][2:]
            kid_item = Kid(title = kid_title, url = kid_url, image_url = kid_image, 
                category = category2, youtube_id = youtube_id)
            kid_item.save()

    if request.META['HTTP_REFERER']:
        url = request.META['HTTP_REFERER']
    else:
        url='/schedule'

    return HttpResponseRedirect(url)

@login_required(login_url=login_url)
def delete(request, kid_id):
    kid_item = get_object_or_404(Kid,id=kid_id)
    if request.user.is_staff:
        kid_item.delete()

    if request.META['HTTP_REFERER']:
        if 'detail' in request.META['HTTP_REFERER']:
          url = '/'
        else:
          url = request.META['HTTP_REFERER']
    else:
        url='/'

    return HttpResponseRedirect(url)

def detail(request, kid_id):
    kid_item = get_object_or_404(Kid,id=kid_id)
    kid_item.view_count += 1
    kid_item.save()

    my_click = False

    try:
        if request.user.is_anonymous:
            kid_user=None
        else:
            kid_user = KidUser.objects.get(kid_user=request.user)
        favorite = Favorite.objects.get(fav_kid=kid_item, fav_user=kid_user)
        if favorite:
            my_click = True
    except:
        favorite = None

    like_count = Favorite.objects.filter(fav_kid=kid_item).count()
    category1 = Category1.objects.order_by('title')

    return render(request,'detail.html', {
        'category1' : category1, 
        'kid' : kid_item, 
        'like_count': like_count,
        'view_count' : kid_item.view_count,
        'my_click' : my_click})

@login_required(login_url=login_url)
def detail_like(request, kid_id):
    kid_user = KidUser.objects.get(kid_user=request.user)
    fav_kid = Kid.objects.get(id=kid_id)
    my_click = False
    try:
        favorite = Favorite.objects.get(fav_kid=fav_kid, fav_user=kid_user)
    except:
        favorite = None

    if favorite:
        favorite.delete()
    else:
        Favorite.objects.create(fav_kid=fav_kid, fav_user=kid_user)
        my_click = True

    like_count=Favorite.objects.filter(fav_kid=kid_id).count()

kid/templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        {% include "header.html" %}
        {% block external %}{% endblock %}
        <link rel="stylesheet" href="/static/kids.css">
    </head>
    <body>
        {% include "menu.html"  %}
        {% block head %}{% endblock %}
        {% block content %}{% endblock %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
<script src="/static/kids.js"></script>

    </body>
</html>

kid/templates/contact.html
{% extends "base.html" %}
{% block content %}  
<div class="white-box">
    <h1>Contact us</h1>
    <br />
    <p>Homepage (<a href="http://shsong97.blogspot.com">http://shsong97.blogspot.com)</a>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="https://shsong97.blogspot.com" data-via="shsong97" data-lang="en">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>
    <p>Song Seung-hun (<a href="mailto:shsong97@gmail.com">shsong97@gmail.com)</a></p>
    <p>Git hub (<a href="http://github.com/shsong97">http://github.com/shsong97)</a></p>
</div>
{% endblock %}

kid/templates/detail.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}{{ kid.title }} {% endblock %}
{% block content %}
<style>
  /* Large devices (large desktops, 1200px and up) */
  @media screen and (min-width: 1200px) {
    #iframe-youtube { width:970px; height:540px; }
  }

  /* Medium devices (desktops, 992px and up) */
  @media screen and (min-width: 992px) and (max-width:1200px) {
    #iframe-youtube { width:970px; height:540px; }
  }

  /* Small devices (tablets, 768px and up) */
  @media screen and (min-width: 768px) and (max-width:992px) {
    #iframe-youtube { width:640px; height:360px; }
  }

  @media screen and (max-width: 768px) {
    #iframe-youtube { width:100%; height:360px; }
  }
  .btn-display {
  	padding: 6px 12px 6px 12px;
  	background-color: #ffffff;
  	display: inline-block;
  	text-decoration: none;
  	width: 60px;
  	text-align: center;
  	border: 0 solid transparent;
  	border-style: none;
  }
  .btn-like {
  	color: red;
  }
  .btn-unlike  {
  	color:black;
  }
  .bottom-line {
  	border-bottom: 1px solid #e2e2e2;
  	padding-bottom: 1px;
  	margin-bottom: 10px;
  }
</style>
<div class="white-box form-group">
    <div class="text-center">
      <iframe id="iframe-youtube" src="https://www.youtube.com/embed/{{ kid.youtube_id }}" frameborder="0" allowfullscreen></iframe>
    </div>
  <br />
  <h4>{{ kid.title }}</h4>
  <div class="text-right bottom-line"><h4>조회수 {{ view_count|intcomma }} 회</h4></div>
  <div class="row">
    <div class="left col-sm-6 col-md-6">
    
    </div>
    <div class="text-right col-sm-6 col-md-6">
      {% if user.is_authenticated %}
      <button class="btn-display btn-{% if my_click %}like{%else%}unlike{% endif %}" id="button_like"><i class="glyphicon glyphicon-heart"></i> <span id="span_like" value="{{ kid.id }}">{{like_count}}</span></button>
      {% endif %}
      {% if user.is_staff %}
      <a href="/delete/{{ kid.id }}" class="btn-display">삭제</a>
      {% endif %}
    </div>
  </div>  

</div>
{% endblock %}

kid/templates/feed.html
{{ obj.title }}

kid/templates/header.html
{% load staticfiles %}
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="kids-tv channel">
<meta name="author" content="Song, Seung-hun">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
<!-- Optional theme -->
<style type="text/css">
    body {
        padding-top: 0;
        margin : 0;
        padding-bottom: 20px;
        background-color:#eee; 
    }
    .white-box { 
        background-color:white; 
        margin:5px; 
        border-color: #1ef;
        border-radius:5px;
        padding:10px;
        border:1px solid #ccc;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

kid/templates/menu.html
<script>
    function goto(page)
    {
        window.location=page;
    }
</script>
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Nav</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">KidsTV</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            {% for cat1 in category1 %}
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            {{ cat1.title }}
            </a>
            <ul class="dropdown-menu">
                {% for cat2 in cat1.category2_set.all %}
                <li role="presentation"><a href="/watch/{{ cat1.title }}/{{ cat2.title }}" role="menuitem">{{ cat2.title }}</a></li>
                {% endfor %}
            </ul>
            </li>
            {% endfor %}
        </ul>
        <ul class="nav navbar-nav" style="float:right">
            {% if user.username %}
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                <ul class="dropdown-menu">
                <li role="presentation"><a href="/myfavorite">즐겨찾기</a></li>
                <li role="presentation"><a href="/profile">사용자 정보</a></li>
                <li role="presentation"><a href="/changepassword">비밀번호 변경</a></li>
                <li role="presentation"><a href="/resetpassword">비밀번호 초기화</a></li>
                {% if user.is_staff %}
                <li role="presentation"><a href="/admin">관리자</a></li>
                {% endif %}
                {% if perms.kid.add_kid %}
                <li role="presentation"><a href="/schedule">항목등록</a></li>
                {% endif %}
                </ul>   
            </li>
            
            <li><button type="button" class="btn btn-danger navbar-btn" onClick="javascript:goto('/logout')">로그아웃</button>
            </li>
            {% else %}
            <li><button type="button" class="btn btn-success navbar-btn" onClick="javascript:goto('/login')">로그인</button>
            <button type="button" class="btn btn-danger navbar-btn" onClick="javascript:goto('/register')">아이디등록</button>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>    
 

kid/templates/myfavorite.html
{% extends "base.html" %}
{% block title %}즐겨찾기{% endblock %}
{% block content %}

<div class="white-box">

<form action="." class="form-search">
    <div class="input-group">
      <input type="text" class="input-medium form-control" name="search_field" value="{{ search_field }}" placeholder="검색어를 입력하세요">
      <span class="input-group-btn">
      <button class="btn btn-success" type="submit">Search</button>
      </span>
  </div>
</form>
</div>
{% for myfavor in myfavorites %}
<div class="white-box">
    <div class="media">
        <div class="media-left media-middle">
            <a href="{% url 'detail' myfavor.fav_kid.id %}" ><img src="{{ myfavor.fav_kid.image_url }}" width="128px"></a>
        </div>
        <div class="media-body">
            <div class="row">
                <div class="col-sm-10">
                    <a href="{% url 'detail' myfavor.fav_kid.id %}" >{{ myfavor.fav_kid.title }}</a>
                </div>
                <div class="col-sm-2">
                    <a href="{% url 'mydelete' myfavor.fav_kid.id %}" class="btn btn-danger right">삭제</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% if show_paginator %}
<nav style="text-align:center">
    <ul class="pagination">
    {% if has_prev10 %}
    <li><a href="?search_field={{ search_field }}&page={{ prev_page10 }}">&laquo;</a></li>
    {% endif %}
    {% if has_prev %}
    <li><a href="?search_field={{ search_field }}&page={{ prev_page }}">&lt;</a></li>
    {% endif %}
    {% for page_id in page_list %}
        {% if page == page_id %}
        <li class="active"><a><b>{{ page_id }}</b></a></li>
        {% else %}
        <li><a href="?search_field={{ search_field }}&page={{ page_id }}">{{ page_id }}</a></li>
        {% endif %}
    {% endfor %}
    {% if has_next %}
    <li>
    <a href="?search_field={{ search_field }}&page={{ next_page }}">&gt;</a></li>
    {% endif %}
    {% if has_next10 %}
    <li>
    <a href="?search_field={{ search_field }}&page={{ next_page10 }}">&raquo;</a></li>
    {% endif %}    
    </ul>
</nav>
{% endif %}

{% endblock %}